### ISSUE TITLE
Error when verifying splits

### ISSUE THREAD

**Issue by thx4ever** [wwww-wwww/grav1_ex#2]
Hi, i got this error when program finish spliting it tries to verify the splits but it trow this error and the program dont continue

[error] GenServer Grav1.ProjectsExecutor terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for %{file: "
00000.mkv", length: 1745, start: 0} of type Map
    (elixir 1.11.4) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.11.4) lib/string/chars.ex:22: String.Chars.to_string/1
    (grav1 0.1.0) lib/grav1/split.ex:254: anonymous fn/7 in Grav1.Split.verify_s
plit/4
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (grav1 0.1.0) lib/grav1/split.ex:215: Grav1.Split.verify_split/4
    (grav1 0.1.0) lib/grav1/split.ex:122: Grav1.Split.split/5
    (grav1 0.1.0) lib/grav1/projects.ex:656: Grav1.ProjectsExecutor.do_action/2
    (grav1 0.1.0) lib/grav1/projects.ex:737: Grav1.ProjectsExecutor.handle_cast/
2
    (stdlib 3.8) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.8) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.8) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :loop}
State: %{}

**Comment by wwww-wwww** [comment]
Thanks for reporting this error. This should fix it, though I recommend installing Vapoursynth since I also only test that path :)

**Comment by thx4ever** [comment]
Thanks too but another error, i have vapoursynth installed and all tools avaliable

iex(1)> [error] GenServer Grav1.ProjectsExecutor terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:ffmpeg,
 1852} of type Tuple
    (elixir 1.11.4) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.11.4) lib/string/chars.ex:22: String.Chars.to_string/1
    (grav1 0.1.0) lib/grav1/split.ex:253: anonymous fn/7 in Grav1.Split.verify_s
plit/4
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (grav1 0.1.0) lib/grav1/split.ex:215: Grav1.Split.verify_split/4
    (grav1 0.1.0) lib/grav1/split.ex:122: Grav1.Split.split/5
    (grav1 0.1.0) lib/grav1/projects.ex:656: Grav1.ProjectsExecutor.do_action/2
    (grav1 0.1.0) lib/grav1/projects.ex:737: Grav1.ProjectsExecutor.handle_cast/
2
    (stdlib 3.8) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.8) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.8) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :loop}
State: %{}

Installed
Python 3.8.8
nodejs 13.14.0
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.11.4 (compiled with Erlang/OTP 21)
All available tools ffmpeg, vpxenc, aomenc, svt_av1, opepass_keyframes
PostgreeSQL-12

**Comment by thx4ever** [comment]
fixed
