### ISSUE TITLE
Incorret splits

### ISSUE THREAD

**Issue by thx4ever** [wwww-wwww/grav1_ex#3]
Hi, So far this program is working great but it have one problem when splitting the video, it split sometimes correctly sometimes no like when it splits the last split have a size about same as source
Can u check this?

Regards

thx4ever

**Comment by wwww-wwww** [comment]
By size do you mean the length of the split or the file size?

**Comment by thx4ever** [comment]
I can confirm that the problem are on mkv scene detecting, when i remux the file to m2ts same problem. I think the problem come from scene detecting  code that cause aomenc-onepass_keyframes crash and ffmpeg start splitting wrong, i tested again with another file and it worked, the input file seems ok for ffmpeg

**Comment by thx4ever** [comment]
My file are MKV source

**Comment by wwww-wwww** [comment]
Can you provide a sample file that doesn't work?

**Comment by thx4ever** [comment]
OK, i have uploaded the file here
https://drive.google.com/file/d/1ey66vUgZeXJNYWNq-qtI8co7OlbpQ761/view?usp=sharing

**Comment by wwww-wwww** [comment]
There seems to be some corrupt frames in your file. Ignoring them might be okay. The client should also be updated accordingly.

**Comment by thx4ever** [comment]
Alright, thanks for the update, its possible to you add error in log so we know when source have problems?

Regards
thx4ever

**Comment by wwww-wwww** [comment]
Probably, but it's not a priority for me. That kind of problem is also a bit out of reach for this project. The program shouldn't make any other assumptions other than the inputs provided by the user are correct.
